events {}

http {

  # Portfolio - Main Domain
  server {
    listen 80;
    server_name chaitanyadev.in;

    location / {
      proxy_pass http://portfolio:80;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Build Dashboard - Subdomain
  server {
    listen 80;
    server_name androidci.chaitanyadev.in;

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Backend API - Subdomain
  server {
    listen 80;
    server_name api.chaitanyadev.in;

    location / {
      proxy_pass http://backend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}
